# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expected_survival <- function(lp, surv_rate) {
    .Call(`_COMETopt_expected_survival`, lp, surv_rate)
}

